# Use a Python image as a base
FROM python:3.11.5

#############################
# Set the working directory #
#############################
WORKDIR /app

###########################################
# Copy necessary files into the container #
###########################################
COPY Python_code Python_code
COPY images images
COPY images /app/Python_code/images
COPY requirements.txt requirements.txt

################################
# Install project dependencies #
################################
RUN rm -rf /app/images
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

#######################################################################
# Command to execute the Python program when the container is started #
#######################################################################
CMD ["python3", "Python_code/Program_Start.py"]
