FROM rootproject/root:latest

WORKDIR /app

# Installa le dipendenze necessarie
RUN apt-get update && apt-get install -y libblas3 libtmva-dev

# Copia la cartella TMVA nel container Docker
COPY ROOT_Gen/ ROOT_Gen/
COPY TMVA_ML/ TMVA_ML/

# Esegui il codice Root dentro alla cartella TMVA
RUN root -l -q 'ROOT_Gen/Generation_Images.C(1000, 16, 16)'

# Copia la cartella images dentro a TMVA_ML
RUN cp -r images/ TMVA_ML/

# Comando predefinito per il container
CMD ["bash"]
