FROM ubuntu:22.04

WORKDIR /app

SHELL ["/bin/bash", "-c"]

COPY ../images images
COPY DataPreparation DataPreparation
COPY Evaluation Evaluation
COPY Models Models
COPY Program_Start.py Program_Start.py

# Update the system
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y graphviz

# Install basic editor
RUN apt-get install -y vim

# Install python and pip
RUN apt-get install -y python3 python3-pip

# Install pkg-config and HDF5 dependencies
RUN apt-get install -y pkg-config libhdf5-dev

# Upgrade pip and install python dependencies
RUN pip3 install --upgrade pip
RUN pip3 install scikit-learn matplotlib pandas numpy
RUN pip3 install uproot tensorflow torch xgboost h5py

# Command to execute the Python program when the container is started
CMD ["python3", "Program_Start.py"]

